#!/usr/bin/env python3
"""
THE FORGE AI - Code Generator
Supports 20+ programming languages
"""

import sys
from pathlib import Path

LANGUAGES = {
    'python': {'ext': '.py', 'comment': '#'},
    'javascript': {'ext': '.js', 'comment': '//'},
    'typescript': {'ext': '.ts', 'comment': '//'},
    'java': {'ext': '.java', 'comment': '//'},
    'cpp': {'ext': '.cpp', 'comment': '//'},
    'c': {'ext': '.c', 'comment': '//'},
    'csharp': {'ext': '.cs', 'comment': '//'},
    'go': {'ext': '.go', 'comment': '//'},
    'rust': {'ext': '.rs', 'comment': '//'},
    'php': {'ext': '.php', 'comment': '//'},
    'ruby': {'ext': '.rb', 'comment': '#'},
    'swift': {'ext': '.swift', 'comment': '//'},
    'kotlin': {'ext': '.kt', 'comment': '//'},
    'dart': {'ext': '.dart', 'comment': '//'},
    'r': {'ext': '.r', 'comment': '#'},
    'scala': {'ext': '.scala', 'comment': '//'},
    'perl': {'ext': '.pl', 'comment': '#'},
    'bash': {'ext': '.sh', 'comment': '#'},
    'powershell': {'ext': '.ps1', 'comment': '#'},
    'lua': {'ext': '.lua', 'comment': '--'},
}

def generate_code(language: str, description: str, filename: str = None):
    """Generate code in specified language"""
    
    if language not in LANGUAGES:
        print(f"✗ Unsupported language: {language}")
        print(f"Supported: {', '.join(LANGUAGES.keys())}")
        return
    
    lang_info = LANGUAGES[language]
    
    if not filename:
        filename = f"generated{lang_info['ext']}"
    
    # Generate code based on description
    code = generate_code_content(language, description, lang_info)
    
    # Save to file
    with open(filename, 'w') as f:
        f.write(code)
    
    print(f"✓ Generated {language} code: {filename}")
    print(f"  Description: {description}")

def generate_code_content(language: str, description: str, lang_info: dict) -> str:
    """Generate actual code content"""
    
    comment = lang_info['comment']
    
    # Basic template
    code = f"""{comment} Generated by THE FORGE AI
{comment} Language: {language}
{comment} Description: {description}
{comment} Generated: {Path(__file__).name}

"""
    
    # Add language-specific code
    if language == 'python':
        code += f"""def main():
    &quot;&quot;&quot;
    {description}
    &quot;&quot;&quot;
    print("Hello from THE FORGE AI!")
    print("Description: {description}")
    
    # TODO: Implement your logic here
    pass

if __name__ == '__main__':
    main()
"""
    elif language in ['javascript', 'typescript']:
        code += f"""function main() {{
    // {description}
    console.log("Hello from THE FORGE AI!");
    console.log("Description: {description}");
    
    // TODO: Implement your logic here
}}

main();
"""
    elif language == 'java':
        code += f"""public class Generated {{
    public static void main(String[] args) {{
        // {description}
        System.out.println("Hello from THE FORGE AI!");
        System.out.println("Description: {description}");
        
        // TODO: Implement your logic here
    }}
}}
"""
    else:
        code += f"""{comment} TODO: Implement {description}
{comment} Add your code here
"""
    
    return code

def main():
    import argparse
    
    parser = argparse.ArgumentParser(description='THE FORGE AI - Code Generator')
    parser.add_argument('language', choices=list(LANGUAGES.keys()), help='Programming language')
    parser.add_argument('description', help='What the code should do')
    parser.add_argument('--output', '-o', help='Output filename')
    
    args = parser.parse_args()
    
    generate_code(args.language, args.description, args.output)

if __name__ == '__main__':
    main()
