"""Linux-style command interface with generative AI features."""

from typing import List, Dict, Any, Optional, Callable
import logging
import subprocess
from pathlib import Path
from dataclasses import dataclass

from kimi_k2.core.config import CommandsConfig


logger = logging.getLogger(__name__)


@dataclass
class Command:
    """Represents a command with metadata."""
    name: str
    description: str
    handler: Callable
    dangerous: bool = False
    category: str = "general"


class ScriptGenerator:
    """AI-powered script generation."""
    
    def generate_script(self, description: str, language: str = "bash") -> str:
        """Generate a script from natural language description.
        
        Args:
            description: Natural language description of what script should do
            language: Target scripting language
            
        Returns:
            Generated script content
        """
        logger.info(f"Generating {language} script: {description}")
        
        # Placeholder for actual AI generation
        script_templates = {
            "bash": "#!/bin/bash\n# {description}\necho 'Script generated by Kimi-K2'\n",
            "python": "#!/usr/bin/env python3\n# {description}\nprint('Script generated by Kimi-K2')\n",
        }
        
        template = script_templates.get(language, script_templates["bash"])
        return template.format(description=description)


class CommandInterface:
    """Main command interface with Linux-style commands."""
    
    def __init__(self, config: CommandsConfig):
        """Initialize command interface.
        
        Args:
            config: Commands configuration
        """
        self.config = config
        self.script_dir = Path(config.script_dir)
        self.script_dir.mkdir(parents=True, exist_ok=True)
        
        self.script_generator = ScriptGenerator()
        self.commands: Dict[str, Command] = {}
        self.command_history: List[str] = []
        
        self._register_builtin_commands()
        logger.info("Command interface initialized")
        
    def _register_builtin_commands(self) -> None:
        """Register built-in commands."""
        self.register_command(
            name="ls",
            description="List directory contents",
            handler=self._cmd_ls,
            category="filesystem"
        )
        
        self.register_command(
            name="gen-script",
            description="Generate script from description",
            handler=self._cmd_gen_script,
            category="ai"
        )
        
        self.register_command(
            name="help",
            description="Show available commands",
            handler=self._cmd_help,
            category="system"
        )
        
    def register_command(
        self,
        name: str,
        description: str,
        handler: Callable,
        dangerous: bool = False,
        category: str = "general"
    ) -> None:
        """Register a new command.
        
        Args:
            name: Command name
            description: Command description
            handler: Function to handle command execution
            dangerous: Whether command is potentially dangerous
            category: Command category
        """
        if dangerous and not self.config.allow_dangerous:
            logger.warning(f"Skipping dangerous command '{name}' (not allowed by config)")
            return
            
        self.commands[name] = Command(
            name=name,
            description=description,
            handler=handler,
            dangerous=dangerous,
            category=category
        )
        logger.debug(f"Registered command: {name}")
        
    def execute_command(self, command_line: str) -> Dict[str, Any]:
        """Execute a command.
        
        Args:
            command_line: Full command line to execute
            
        Returns:
            Command execution result
        """
        self.command_history.append(command_line)
        
        parts = command_line.strip().split()
        if not parts:
            return {"success": False, "error": "Empty command"}
            
        cmd_name = parts[0]
        args = parts[1:]
        
        if cmd_name not in self.commands:
            return {"success": False, "error": f"Unknown command: {cmd_name}"}
            
        command = self.commands[cmd_name]
        
        try:
            result = command.handler(args)
            return {"success": True, "result": result}
        except Exception as e:
            logger.error(f"Command execution failed: {e}")
            return {"success": False, "error": str(e)}
            
    def _cmd_ls(self, args: List[str]) -> str:
        """List directory contents."""
        path = args[0] if args else "."
        path_obj = Path(path)
        
        if not path_obj.exists():
            return f"Error: {path} not found"
            
        items = list(path_obj.iterdir())
        return "\n".join(item.name for item in items)
        
    def _cmd_gen_script(self, args: List[str]) -> str:
        """Generate script from description."""
        if not args:
            return "Error: Please provide a description"
            
        description = " ".join(args)
        script_content = self.script_generator.generate_script(description)
        
        # Save to file
        script_name = f"generated_{len(self.command_history)}.sh"
        script_path = self.script_dir / script_name
        script_path.write_text(script_content)
        script_path.chmod(0o755)
        
        return f"Generated script: {script_path}"
        
    def _cmd_help(self, args: List[str]) -> str:
        """Show available commands."""
        categories: Dict[str, List[Command]] = {}
        
        for cmd in self.commands.values():
            if cmd.category not in categories:
                categories[cmd.category] = []
            categories[cmd.category].append(cmd)
            
        output = ["Available Commands:", ""]
        
        for category, cmds in sorted(categories.items()):
            output.append(f"[{category.upper()}]")
            for cmd in sorted(cmds, key=lambda c: c.name):
                danger_marker = " [DANGEROUS]" if cmd.dangerous else ""
                output.append(f"  {cmd.name:15} - {cmd.description}{danger_marker}")
            output.append("")
            
        return "\n".join(output)
        
    def shutdown(self) -> None:
        """Cleanup command interface resources."""
        logger.info("Shutting down command interface")
